language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
  - jruby-9.1.6.0
env:
  - LONG_RUN=true
matrix:
  include:
    - rvm: 2.0
      gemfile: Gemfile_ruby2
      before_install:
        - gem install bundler -v '< 2'
    - rvm: 2.1
      gemfile: Gemfile_ruby2
      before_install:
        - gem install bundler -v '< 2'
    - rvm: 2.6
      env: RUBYOPT=--jit LONG_RUN=true
    - rvm: ruby-head
      env: RUBYOPT=--jit LONG_RUN=true
  allow_failures:
    - rvm: ruby-head
    - rvm: ruby-head
      env: RUBYOPT=--jit LONG_RUN=true
    - rvm: jruby-9.1.6.0
bundler_args: --without local_development
